name: adviser
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  get_it: ^7.2.0

dev_dependencies:
  test: ^1.21.4
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  mockito: ^5.3.2


flutter:
  uses-material-design: true
